apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: ghcr.io/<your-username>/<your-repo>/microservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: default
spec:
  selector:
    app: microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP