```python
import autogen
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import json
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch

# Mock Bank Nifty data generator
def generate_mock_banknifty_data(days=30):
    dates = [datetime.now() - timedelta(days=x) for x in range(days)][::-1]
        prices = [52000 + np.random.normal(0, 200) + x * 10 for x in range(days)]
            volumes = [np.random.randint(2000000, 6000000) for _ in range(days)]
                df = pd.DataFrame({'Date': dates, 'Close': prices, 'Volume': volumes})
                    df['5_MA'] = df['Close'].rolling(window=5).mean()
                        df['Volatility'] = df['Close'].rolling(window=5).std()
                            df['RSI'] = compute_rsi(df['Close'], 14)
                                return df
                                
                                # Compute RSI
                                def compute_rsi(data, periods=14):
                                    delta = data.diff()
                                        gain = (delta.where(delta > 0, 0)).rolling(window=periods).mean()
                                            loss = (-delta.where(delta < 0, 0)).rolling(window=periods).mean()
                                                rs = gain / loss
                                                    return 100 - (100 / (1 + rs))
                                                    
                                                    # Load Mistral 7B with 4-bit quantization
                                                    bnb_config = BitsAndBytesConfig(
                                                        load_in_4bit=True,
                                                            bnb_4bit_use_double_quant=True,
                                                                bnb_4bit_quant_type="nf4",
                                                                    bnb_4bit_compute_dtype=torch.bfloat16
                                                                    )
                                                                    
                                                                    model_name = "mistralai/Mixtral-8x7B-Instruct-v0.1"
                                                                    tokenizer = AutoTokenizer.from_pretrained(model_name)
                                                                    model = AutoModelForCausalLM.from_pretrained(
                                                                        model_name,
                                                                            quantization_config=bnb_config,
                                                                                device_map="auto",
                                                                                    low_cpu_mem_usage=True
                                                                                    )
                                                                                    
                                                                                    # Custom inference function for Mistral 7B
                                                                                    def local_llm_inference(prompt):
                                                                                        inputs = tokenizer(prompt, return_tensors="pt").to("cuda" if torch.cuda.is_available() else "cpu")
                                                                                            outputs = model.generate(**inputs, max_new_tokens=500, temperature=0.7)
                                                                                                return tokenizer.decode(outputs[0], skip_special_tokens=True)
                                                                                                
                                                                                                # LLM configuration for AutoGen
                                                                                                llm_config = {
                                                                                                    "functions": [
                                                                                                            {
                                                                                                                        "name": "analyze_banknifty_options",
                                                                                                                                    "description": "Analyze Bank Nifty data and provide trading recommendations",
                                                                                                                                                "parameters": {
                                                                                                                                                                "type": "object",
                                                                                                                                                                                "properties": {},
                                                                                                                                                                                                "required": []
                                                                                                                                                                                                            }
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                            "config_list": [{"model": "mistral-7b", "api_key": "not-needed"}],
                                                                                                                                                                                                                                "request_timeout": 120,
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                # Data Analyst Agent
                                                                                                                                                                                                                                data_analyst = autogen.AssistantAgent(
                                                                                                                                                                                                                                    name="DataAnalyst",
                                                                                                                                                                                                                                        llm_config=llm_config,
                                                                                                                                                                                                                                            system_message="You are a Data Analyst for Bank Nifty options trading. Analyze index data, calculate metrics (e.g., moving average, volatility, RSI), and recommend when to buy or sell options (e.g., Long Call, Long Put, Short Straddle). Return the analysis in JSON format."
                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                            # Report Generator Agent
                                                                                                                                                                                                                                            report_generator = autogen.AssistantAgent(
                                                                                                                                                                                                                                                name="ReportGenerator",
                                                                                                                                                                                                                                                    llm_config=llm_config,
                                                                                                                                                                                                                                                        system_message="You are a Report Generator. Convert the Data Analyst's JSON into a markdown report with sections: Market Overview, Buy/Sell Recommendations, and Risk Management Tips. Make it clear and actionable."
                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                        # Define group chat
                                                                                                                                                                                                                                                        group_chat = autogen.GroupChat(
                                                                                                                                                                                                                                                            agents=[data_analyst, report_generator],
                                                                                                                                                                                                                                                                messages=[],
                                                                                                                                                                                                                                                                    max_round=3
                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                    # Group chat manager
                                                                                                                                                                                                                                                                    group_chat_manager = autogen.GroupChatManager(
                                                                                                                                                                                                                                                                        groupchat=group_chat,
                                                                                                                                                                                                                                                                            llm_config=llm_config
                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                            # Function to analyze Bank Nifty and recommend buy/sell
                                                                                                                                                                                                                                                                            def analyze_banknifty_options(_):
                                                                                                                                                                                                                                                                                df = generate_mock_banknifty_data()
                                                                                                                                                                                                                                                                                    recent_price = df['Close'].iloc[-1]
                                                                                                                                                                                                                                                                                        ma_5 = df['5_MA'].iloc[-1]
                                                                                                                                                                                                                                                                                            volatility = df['Volatility'].iloc[-1]
                                                                                                                                                                                                                                                                                                rsi = df['RSI'].iloc[-1]
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                        trend = "Bullish" if recent_price > ma_5 and rsi < 70 else "Bearish" if recent_price < ma_5 and rsi > 30 else "Range-bound"
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                recommendations = []
                                                                                                                                                                                                                                                                                                                    if trend == "Bullish":
                                                                                                                                                                                                                                                                                                                            recommendations.append({
                                                                                                                                                                                                                                                                                                                                        "action": "Buy",
                                                                                                                                                                                                                                                                                                                                                    "strategy": "Long Call",
                                                                                                                                                                                                                                                                                                                                                                "details": f"Buy a call option at strike {int(recent_price)} due to bullish trend (RSI: {round(rsi, 2)}, Price > 5-MA)."
                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                            elif trend == "Bearish":
                                                                                                                                                                                                                                                                                                                                                                                    recommendations.append({
                                                                                                                                                                                                                                                                                                                                                                                                "action": "Buy",
                                                                                                                                                                                                                                                                                                                                                                                                            "strategy": "Long Put",
                                                                                                                                                                                                                                                                                                                                                                                                                        "details": f"Buy a put option at strike {int(recent_price)} due to bearish trend (RSI: {round(rsi, 2)}, Price < 5-MA)."
                                                                                                                                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                            recommendations.append({
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "action": "Sell",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "strategy": "Short Straddle",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "details": f"Sell a call and put at strike {int(recent_price)} due to range-bound market (RSI: {round(rsi, 2)})."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                risk_management = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Set stop-loss at 2-3% of trading capital.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Avoid options expiring in less than 15 days.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Monitor RSI: Avoid buying if RSI > 70 (overbought) or selling if RSI < 30 (oversold)."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    analysis = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "index": "BANKNIFTY",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "recent_price": round(recent_price, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "5_day_moving_average": round(ma_5, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "volatility": round(volatility, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "rsi": round(rsi, 2),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "trend": trend,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "recommendations": recommendations,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "risk_management": risk_management
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return json.dumps(analysis, indent=2)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Register function for Data Analyst
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            data_analyst.register_function(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function_map={"analyze_banknifty_options": analyze_banknifty_options}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Custom AutoGen client for local LLM
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class CustomLLMClient:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def create(self, params):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            prompt = params.get("prompt", "")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    response = local_llm_inference(prompt)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return {"choices": [{"message": {"content": response}}]}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Assign custom client to agents
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for agent in [data_analyst, report_generator, group_chat_manager]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                agent.llm_client = CustomLLMClient()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Initiate the conversation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def generate_banknifty_recommendations():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    data_analyst.initiate_chat(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            group_chat_manager,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    message="Analyze Bank Nifty data and provide buy/sell options trading recommendations in JSON format."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            generate_banknifty_recommendations()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ```